# -*- coding: utf-8 -*-
"""Python-Basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xjXRrGOLio09C_GBmWacI_82L7yh7ns
"""

print("Hello World")
print(type("Hello World"))

a=2
b=3
print(a+b)
print(type(a+b))

a = input()
b= input()
print(a+b)
print(type(a+b))

a = int(input())
b= int(input())
print(a+b)
print(type(a+b))

a = int(input())
b= input()
print(a+b)
print(type(a+b))

a = int(input())
b= input()
c = a+b
print(c)
print(type(c))

for i in range(1,11):
  print(i)

for i in range(1,15,2):
  print(i)

for i in range(0,15,2):
  print(i)

for i in range(1,15,-1):
  print(i)

for i in range(5,51,5):
  print(i)

i = 1

while i <= 10:
    print(i)
    i += 1

i = 1

while i <= 50:
  if i % 5 == 0:
    print(i)

  i = i+1

i = 0

while i < 50:
    i = i +5
    print(i)

import math

n = int(input("Enter the value of n: "))

print("Prime numbers between 1 and", n, "are:")

for num in range(2, n + 1):
    is_prime = True


    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(num, end=" ")

def hello():
  return("Hello User")


hello()

def sum(a,b,c):
  return(a+b+c)

a= int(input("Enter 1 number:"))
b= int(input("Enter 2 Number:"))
c= int(input("Enter 3 Number:"))

sum(a,b,c)

a = [21,2,3,5,11]

print([i**2 for i in a])

numbers = [3, 1, 4, 1, 5, 9, 2, 6]

squared = list(map(lambda x: x**2, numbers))

a =['lion', 'dog', 'cat', 'wolf', 'tiger']

print(a)

a =['lion', 'dog', 'cat', 'wolf', 'tiger']
for i in a:
  print(i.upper())

a =['lion', 'dog', 'cat', 'wolf', 'tiger']
for idx,animal in enumerate(a,start=1):
  print({idx},{animal})

a =['lion', 'dog', 'cat', 'wolf', 'tiger']


my_dict = dict(enumerate(a))

print(my_dict)

def divisible():
  for i in range(x,y):
    if i%2==0 and i%3==0 and i%5==0:
      print(i)


def div():
  for i in range(x,y):
    if i%6==0 and i%7==0:
      print(i)


x= int(input("Enter the value of starting value: "))
y= int(input("Enter the value of ending value: "))

print("Divisible by 2, 3 and 5:")
divisible()
print("Divisible by 6 and 7")
div()

def divisible():

  for i in range(x,y):
    if i%2==0 or i%3==0 or i%5==0:
      l1.append(i)
  print(l1)


def div():

  for i in range(x,y):
    if i%6==0 or i%7==0:
      l2.append(i)
  print(l2)


x= int(input("Enter the value of starting value: "))
y= int(input("Enter the value of ending value: "))

l1=[]
l2=[]

print("Divisible by 2, 3 and 5: ")
divisible()


print("Divisible by 6 and 7: ")
div()

l3 = l1+l2
print(l3)

l =[2, 3, 4, 5, 6, 8, 9, 10, 12, 14, 15, 16, 18, 6, 7, 12, 14, 18]
print(l[0:10:2])
print(l[::-1])

a = "Anshul"
print(a[::-1])
print(a[5:3:-1])
h = "maheedhar reddy"
print(h[:8:-1])

def greet():
    greet.count += 1

    if greet.count == 1:
        return "Hello"
    elif greet.count == 2:
        return "Hi"
    elif greet.count == 3:
        return "How are you"
    else:
      return "No More Greetings"

greet.count = 0

print(greet())
print(greet())
print(greet())
print(greet())

def hi(num):
    if num == 1:
        print("Hello")

    elif num == 2:
        print("Hi")

    else:
        print("How Are You")

hi(5)

def fun(n1, n2):

    if n1 + n2 == 5:
        l = [1, 2, 3, 4, 5]
        print(l)

    elif n1 + n2 > 5:
        s = {1, 2, 3, 4, 5}
        print(s)

    else:
        l1 = []
        l2 = []

        for i in range(1, 6):
            l1.append(i * n1)

        for i in range(1, 6):
            l2.append(i * n2)

        result = [l1, l2]
        print(result)


n1 = int(input("Enter the value of n1: "))
n2 = int(input("Enter the value of n2: "))

fun(n1, n2)

scores = [88, 92, 75, 60, 95]

# Indexing (0-based from left, -1 from right)
print(scores[0])        # 88
print(scores[-1])       # 95
print(scores[1:4])      # [92, 75, 60]

# Modification
scores.append(85)       # add to end
scores.insert(0, 100)   # insert at index 0
scores.remove(60)       # remove first occurrence of 60
popped = scores.pop()   # removes & returns last element

# Useful methods
print(max(scores))      # highest
print(min(scores))      # lowest
print(sorted(scores))   # sorted copy (original unchanged)
scores.sort()           # sorts IN-PLACE
print(scores.count(88)) # how many times 88 appears

# Basic function
def greet(name):
    return f"Hello, {name}!"

print(greet("Rahul"))       # Hello, Rahul!

# Default parameters
def power(base, exp=2):
    return base ** exp

print(power(3))             # 9   (uses default exp=2)
print(power(3, 3))          # 27

# Multiple return values (returned as tuple)
def stats(numbers):
    total   = sum(numbers)
    average = total / len(numbers)
    return total, average

t, avg = stats([10, 20, 30, 40])
print(f"Total: {t}, Average: {avg}")   # Total: 100, Average: 25.0

# *args — variable number of positional arguments
def add_all(*args):
    return sum(args)

print(add_all(1, 2, 3, 4, 5))   # 15

# **kwargs — variable keyword arguments
def student_info(**kwargs):
    for key, value in kwargs.items():
        print(f"  {key}: {value}")

student_info(name="Aisha", age=22, city="Kochi")

# ── Tuples ────────────────────────────────────────
point = (12.5, 8.3)         # latitude, longitude
x, y  = point               # tuple unpacking
# point[0] = 15             # ❌ TypeError: 'tuple' is immutable

# ── Sets ──────────────────────────────────────────
categories_a = {"Sports", "Tech", "Music", "Tech"}   # duplicates auto-removed
categories_b = {"Health", "Tech", "Finance"}

print(categories_a)          # {'Sports', 'Tech', 'Music'}  (order varies)
print(categories_a | categories_b)  # Union
print(categories_a & categories_b)  # Intersection: {'Tech'}
print(categories_a - categories_b)  # Difference:   {'Sports','Music'}

# Fast membership test — O(1) vs O(n) for list
big_set  = set(range(1_000_000))
print(999_999 in big_set)    # True — instant

# create a project on coffee machine which will print that hash images of that specific classes like late, mocha , americano,etc., where coffe is the abstract class and remaineing are the encapsulater one which is wraped within the coffee and the reciperice of this could be created using inheritnce properties a, write a pyton code to run this coffee code on the terminal.

'''
steps to submit:
create the project,
push it to th git
make a repo in the gitnub and push it publically and share the link of that repo on google classroom.'''

class Student:
    # Class attribute — shared by ALL instances
    institution = "Data Science Institute"

    # __init__ is the constructor; 'self' refers to the instance
    def __init__(self, name, age, marks):
        # Instance attributes — unique to each object
        self.name  = name
        self.age   = age
        self.marks = marks

    # Instance method
    def grade(self):
        if self.marks >= 90:
            return "A+"
        elif self.marks >= 75:
            return "A"
        else:
            return "B"

    # Special method — controls print() output
    def __repr__(self):
        return f"Student(name='{self.name}', marks={self.marks})"


# ── Creating objects (instances) ──
s1 = Student("Priya",  21, 92)   # If the argument is not passed it will give typeerror.
s2 = Student("Arjun",  23, 78)

print(s1.grade())                # A+
print(s2.grade())                # A
print(s1.institution)            # Data Science Institute
print(s2)                        # Student(name='Arjun', marks=78)

class Car:

    def __init__(self, brand, color, milage):
        self.brand = brand
        self.color = color
        self.milage = milage

    def __repr__(self):
        return f"Car: brand='{self.brand}', color='{self.color}', milage={self.milage}"


C1 = Car("Toyota", "Red", 25)
C2 = Car("Honda", "Blue", 30)
C3 = Car("Ford", "Green", 20)
C4 = Car("Tesla", "Black", 35)

print(C1)
print(C2)
print(C3)
print(C4)
print(C1.brand)
print(C2.color)
print(C3.milage)

from abc import ABC, abstractmethod
# Abstract Class
class Car(ABC):
    def __init__(self, color, mileage):
        # Encapsulation
        self.__color = color
        self.__mileage = mileage
    # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Abstract method (Polymorphism)
    @abstractmethod
    def get_info(self):
        pass
# Inheritance
class Tesla(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Tesla Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class BMW(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"BMW Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class Audi(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Audi Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
# Objects
car1 = Tesla("Red", 500)
car2 = BMW("Black", 400)
car3 = Audi("White", 450)

# Polymorphism - same method name, different implementations
cars = [car1, car2, car3]
for car in cars:
    print(car.get_info())

from abc import ABC, abstractmethod
# Abstract Class
class Car(ABC):
    def __init__(self, color, mileage):
        # Encapsulation
        self.__color = color
        self.__mileage = mileage
    # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Abstract method (Polymorphism)
    @abstractmethod
    def get_info(self):
        pass
# Inheritance
class Tesla(Car):
  # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Polymorphism - own implementation
    def get_info(self):
        return f"Tesla Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class BMW(Car):
  # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Polymorphism - own implementation
    def get_info(self):
        return f"BMW Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class Audi(Car):
  # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Polymorphism - own implementation
    def get_info(self):
        return f"Audi Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
# Objects
car1 = Tesla("Red", 500)
car2 = BMW("Black", 400)
car3 = Audi("White", 450)

# Polymorphism - same method name, different implementations
cars = [car1, car2, car3]
for car in cars:
    print(car.get_info())

list = (
    10,                 # int
    3.14,               # float
    "Hello",            # string
    True,               # boolean
    None,               # NoneType
    [1, 2, 3],          # list
    (4, 5, 6),          # tuple
    {"a": 1, "b": 2},   # dictionary
    {7, 8, 9},          # set
    complex(2, 3)       # complex number
)

print(list[3])
print(type(list))
print(type(list[1]))
print(type(list[2]))
print(type(list[3]))
print(type(list[6]))
print(type(list[7]))

import numpy as np


#l1 = [20]   # 0 dimension

l1=[20 ,13 ,57 ,82 ,92]
print(l1)
l2 = [14, 35 , 68, 14, 2]  # 1 dimenstion
print(l2)
l = [l1,l2]
print(l1+l2)
print([l1,l2])

print(l[1][3])

print(l[1:6])
print(l[1:6:2])
print(l[:6])
print(l[1:])
print(l[::-1])

l = [14, 25, 264, 14 , 14 ,14 ,45, 45 , 14 ,89]
print(l[1:6])
print(l[1:6:2])
print(l[:6])
print(l[1:])
print(l[::-1])

import numpy as np

l = np.array([10, 20, 30, 40, 50, 60, 70])

print(l[1:6])     # elements from index 1 to 5
print(l[1:6:2])   # step = 2
print(l[:6])      # from start to index 5
print(l[1:])      # from index 1 to end
print(l[::-1])    # reverse

# 2D same no. of values
import numpy as np

l = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(l)

# Slicing
print(l[1:3])        # rows 1 to 2
print(l[:, 1:3])     # all rows, columns 1 to 2
print(l[::-1])       # reverse rows

import numpy as np

l = np.array([
    [10, 20, 30],
    [40, 50],
    [60, 70, 80, 90]
])

print(l)

# Accessing elements
print(l[0])      # first row
print(l[1][1])   # 50

import numpy as np

v1= np.array([1,2,3,4,5,6,7,8,9,10])


print(v1+5)
print(v1*2)
print(v1[1:5])
print(v1[::-1])
print(v1[0:5:-1])

s = [[1,2,3],[3,4,5],[5,6,7]]

s1= np.array(s)

print(s1[1])
print(s1[2])
print(s1[-1])
print(s1[1][1])
print(s1[1][-1])
print(s1[-1][-2])
print(s1[1][0])
ss= print([[s1],[s1]])

s1[0][0]=12
s2=(s1+s1)
print(s2)

print([[s1],[s1],[s1]])

# sum of two matrix:

A = [[1, 2, 3],
     [4, 5, 6]]

B = [[7, 8, 9],
     [1, 2, 3]]

result = []

for i in range(len(A)):
    row = []
    for j in range(len(A[0])):
        row.append(A[i][j] + B[i][j])
    result.append(row)

print(result)

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [1, 2, 3]])

C = A + B

print(C)

import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6]])

B = np.array([[7, 8],[9, 10],[11, 12]])

C = np.dot(A, B)

print(C)

A = [[1, 2, 3],[4, 5, 6]]

B = [[7, 8],[9, 10],[11, 12]]

result = [[0, 0],[0, 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

print(result)

